# _id, count
exclusion_data = [
("NOOLISFMXDJSKH-KXUCPTDWSA-N", 3137),
("PUZPDOWCWNUUKD-UHFFFAOYSA-M", 1566),
("CIWBSHSKHKDKBQ-JLAZNSOCSA-N", 1377),
("FAPWRFPIFSIZLT-UHFFFAOYSA-M", 1296),
("PUZPDOWCWNUUKD-UHFFFAOYSA-M", 1566),
("WCUXLLCKKVVCTQ-UHFFFAOYSA-M", 1007),
("LFQSCWFLJHTTHZ-UHFFFAOYSA-N", 3398),
    ]

exclusion_ids = [x for x, y in exclusion_data]
