exclusion_ids = [
"NOOLISFMXDJSKH-KXUCPTDWSA-N",
"PUZPDOWCWNUUKD-UHFFFAOYSA-M",
"CIWBSHSKHKDKBQ-JLAZNSOCSA-N",
"FAPWRFPIFSIZLT-UHFFFAOYSA-M",
"PUZPDOWCWNUUKD-UHFFFAOYSA-M",
"WCUXLLCKKVVCTQ-UHFFFAOYSA-M",
"LFQSCWFLJHTTHZ-UHFFFAOYSA-N",
]
