# _id, name, count
exclusion_ids = [
"FAPWRFPIFSIZLT-UHFFFAOYSA-M", #"(sodium chloride),(Sodium Chloride),(Sodium Chloride),(Sodium Chloride)", 4530),
"MYMOFIZGZYHOMD-UHFFFAOYSA-N", #"(dioxygen),(Oxygen),(dioxygen)", 4486),
"VTHJTEIRLNZDEV-UHFFFAOYSA-L", #"(Magnesium Hydroxide)", 3942),
"DE08037SAB", #"(Magnesium Sulfate)", 3285),
"LNIZKKFWMDARJV-UHFFFAOYSA-H", #"(Calcium Citrate)", 3225),
"HCHKCACWOHOZIP-UHFFFAOYSA-N", #"(zinc atom),(Zinc)", 2567),
"V146K8QJ07", #"(polyethylene glycol 9000)", 2209),
"BUGBHKTXTAQXES-UHFFFAOYSA-N", #"(Selenium)", 1923),
"LFQSCWFLJHTTHZ-UHFFFAOYSA-N", #"(ethanol),(Ethanol),(ethanol),(ALCOHOL),(Ethanol),(Ethanol)", 1741),
"T5L8T28FGP", #"(Mineral Oil)", 1633),
"490D9F069T", #"()", 1595),
"KDXKERNSBIXSRK-YFKPBYRVSA-N", #"(L-lysine),(Lysine)", 1585),
"SCVFZCLFOSHCOH-UHFFFAOYSA-M", #"(Potassium Acetate)", 1584),
"89DS0H96TB", #"(Zinc Sulfate)", 1563),
"9GB927LAJW", #"()", 1543),
"PLSARIKBYIPYPF-UHFFFAOYSA-H", #"(magnesium citrate)", 1529),
"PUZPDOWCWNUUKD-UHFFFAOYSA-M", #"(Neutral Sodium Fluoride),(Sodium fluoride),(Sodium Fluoride),(Sodium fluoride)", 1497),
"QTBSBXVTEAMEQO-UHFFFAOYSA-M", #"(acetate),(Acetate)", 1487),
"XLYOFNOQVPJJNP-UHFFFAOYSA-N", #"(water),(water),(water),(water),(water),(Water),(water)", 1484),
"XSQUKJJJFZCRTK-UHFFFAOYSA-N", #"(urea),(Urea)", 1368),
"PNDPGZBMCMUPRI-UHFFFAOYSA-N", #"(Iodine)", 1349),
"YGSDEFSMJLZEOE-UHFFFAOYSA-N", #"(salicylic acid),(Salicylic acid),(Salicylic Acid),(Salicylic acid)", 1218),
"BBL281NWFG", #"(Cod Liver Oil)", 1204),
"L7T10EIP3A", #"(Menthol)", 1200),
"RYGMFSIKBFXOCR-UHFFFAOYSA-N", #"(copper atom),(Copper)", 1143),
"RNWHGQJWIACOKP-UHFFFAOYSA-N", #"(Zinc Oxide)", 1133),
"R17X820ROL", #"()", 1008),
"84XB4DV00W", #"(Linseed Oil)", 2368)
    ]
