#!/usr/bin/env bash

sname=$0
HOST="localhost:9200"
VERBOSE=0

function usage {
    printf "Usage: $sname [-hvs] <script JSON path>\n"
    printf "  -h|--help                Display help\n"
    printf "  -v|--verbose             Verbose on\n"
    printf "  -s|--host                'Server:Port' string to store script on, defaults to 'localhost:9200'\n"
    exit $1
}

for flag in "$@"
do
case $flag in
    -s=*|--host=*)
    HOST="${flag#*=}"
    shift
    ;;
    -v|--verbose)
    VERBOSE=1
    shift
    ;;
    -h|--help)
    usage 0
    ;;
    *)

    ;;
esac
done

if [ "$#" -ge 1 ]; then
    if [[ -n $1 ]] && [[ -e $1 ]]; then
        script_path=$1
    else
        printf "ERROR: Script JSON must exist\n\n"
        usage 1
    fi
else
    printf "ERROR: Script JSON path required\n\n"
    usage 1
fi

if [ "$VERBOSE" -eq 1 ]; then
    printf "\n\n"
    echo curl -H'Content-Type: application/json' -XPOST 'http://'"${HOST}"'/_scripts/truncate-large-fields'
    printf "\n\n${script}\n\n"
fi

cd

curl -XPOST 'http://'"${HOST}"'/_scripts/truncate-large-fields' -H'Content-Type: application/json' -d @"${script_path}"
